# 公開するページのURL
baseURL = "https://csreviser.github.io/CS2-blog"

languageCode = "ja"
DefaultContentLanguage = "ja"
HasCJKLanguage = true
enableRobotsTXT = true

# ブログのタイトル
title = "語学講座CS2のブログ"

theme = "mainroad"
paginate = 20

# 自己紹介
[Author]
    name = "CSReviser"
    bio = "語学講座CS2のブログです"
    avatar = "https://avatars.githubusercontent.com/u/46049273?s=96&v=4"

[Params]
    customCSS = ["css/custom.css"]
    copyright = "Author"
    readmore = true
    authorbox = true
    post_meta = ["date", "categories"]
    twitter_cards = true

# ページのテーマカラー
[Params.style.vars]
  highlightColor = "#e22d30"

# SNS等のユーザー名
[Params.widgets.social]
  twitter = "CSReviser"
  github = "CSReviser/CaptureStream2"

[[Params.widgets.social.custom]]
    title = "My Home Page"
    url = "https://csreviser.github.io/CaptureStream2/"
#  icon = "https://avatars.githubusercontent.com/u/46049273?v=4"

[[Parmas.widgets.social.custom]]
    title = "X (旧Twitter)"
    url = "https://x.com/CSReviser"

[Params.sidebar]
    home = "right"
    list = "right"
    single = "right"
    widgets = ["search", "recent", "categories", "taglist", "social"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
  posts = '/:year/:month/:day/'
      
[outputs]
  home = [ "HTML", "AMP", "RSS" ]
  page = [ "HTML", "AMP", "RSS" ]
  section = ["JSON", "HTML", "RSS"]
